type DWLRStation @table {
  stationId: UUID
  name: String!
  latitude: Float!
  longitude: Float!
  state: String!
  district: String!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  installationDate: Date
  notes: String
}

type GroundwaterReading @table {
  readingId: UUID
  timestamp: Timestamp!
  waterLevel: Float!
  createdAt: Timestamp!
  dwlrStation: DWLRStation
}

type User @table {
  userId: UUID
  username: String!
  email: String!
  createdAt: Timestamp!
  displayName: String
  preferences: String
  subscriptionType: SubscriptionType
}

type FavoriteStation @table(key: ["user", "dwlrStation"]) {
  user: User!
  dwlrStation: DWLRStation!
  createdAt: Timestamp!
}

type SubscriptionType @table {
  typeId: UUID
  name: String!
  description: String!
  features: [String]
  price: Float
  duration: Int
}